### ISSUE TITLE
Add the ability to prefer either RF or TUNNEL uplinks

### ISSUE THREAD

**Issue by dranch** [aredn/aredn#409] opened 2022-06-24 20:09 UTC
Per the request from Orv W6BI, Orv mentioned the following new functionality in the AREDN daily builds:

"The very latest nightly build now has LQM able to measure quality on non-RF links.  With that enabled, we SHOULD be able to run dual links between two sites.   LQM will only use the best quality link.  If it goes away, it SHOULD flip to the remaining route.    Someone needs to test that"

My request is:

I think it would be beneficial if users could somehow configure routing weights so they could set their own egress preference be it their RF uplink or Internet tunnel uplink.  I know this could go against the AREDN mantra of keeping it simple but details like this have been sorely missing IMHO as sometimes there is other circumstances here and while the Internet link might be more reliable, we want to use the RF link whenever possible and only use the Internet tunnel or tunnels as a last-resort backup ONLY.

**Comment by ae6xe** [comment] 2022-06-24 21:39
LQM is turning a link on or off based on various conditions.   In this case if there are 2 paths direct between neighbors, RF and hard cable, we can turn one path off, the RF,  to take out of the equation.   Its always the case direct between nodes that RF emissions is unnecessay and less through put than a physical cable.  ...until the direct cable path is no longer functioning.   

A tunnel often connects 2 mesh islands together, and there generally wouldn't be 2 paths between the islands to benefit from this feature.

In another situation, tunnels jump within a given mesh rf island.  I can see benefit to increase the cost of routing over a tunnel to force traffic to go over RF links.  We need to know that if the Internet goes down in our local area, we can still provide services.  

I have a single hop high quality  RF back bone link that users have 3 tunnels jumping around it right now, it is problematic.  This feature would need to be deployed by another admin. it's not my node where the route path is diverting to tunnels.  But I can see benefit for this feature, if I can get others to agree.

In another situation, the tunnel was specifcally setup to jump over a weak RF link.    This feature wouldnt be needed. 

What situations are you thinking of?

**Comment by dranch** [comment] 2022-06-24 22:04
The primary use case is:
   1. I have a high level node that first started with an Internet tunnel only.  We later established an RF uplink into the same mesh but we kept the Internet tunnel as a backup.  I personally want to force all traffic over the RF link and *only* resort to using the tunnel if the RF link goes down.
 
Since you mentioned it, there is a renewed question around having *redundant* Internet tunnels into the same mesh with the new LQM functionality.  The reason here is that in the above mentioned Internet tunnel, it has gone down for extended periods multiple times and our "provider" didn't know until I emailed him.  Not great but reality for the network.  To mitigate this, I would like to have TWO internet tunnels from different upstream "providers".  It might be nice to also set metrics or weights on each of those tunnels so I can have a primary tunnel and secondary or backup tunnel though it might be better to let OLSR route table pick the shortest path for a given destination.

**Comment by aanon4** [comment] 2022-07-13 00:32
So if the tunnel and the RF link were both between exactly the same nodes, LQM could be made to block the tunnel if the RF link was up. However, anything more sophisticated (such as the tunnel going to a different node from the RF link) is beyond its comprehension.

**Comment by KI7ODK** [comment] 2022-07-17 15:09
The Miami Valley Microwave Alliance in Dayton has found another possible reason for wanting to weight RF links more heavily over tunnels. It is true that tunnels will almost always have a higher data throughput capacity than RF. However, in our experience, we have found that latency over RF links can often be many times lower than that of tunnels. Any time you traverse the internet, you will incur round-trip times of at least 40 ms nominally. Our RF links routinely have round trip times of 10 ms or less nominally.

[See the linked message archive for some route samples done by NC8Q.](http://mailman.qth.net/pipermail/mvma/Week-of-Mon-20220530/001405.html)

**Comment by cTurtle98** [comment] 2022-07-31 19:44
it would be really cool to have a checkbox for "prefer rf and d2d over tunnels" and then we can make redundant tunnel connections

**Comment by aanon4** [comment] 2022-08-01 15:56
The problem here is one of requirements - if a tunnel is only active at a particular time, when is that? There are ways to tweak preferring RF over tunnels, but I can see some people not wanting the tunnel active unless absolutely necessary (ie. the pay for the bandwidth). So I think there may be two things here:
1. Prefer RF to tunnels when both are active
2. Active a tunnel only under specific conditions
Should the first always be the case?
What are the conditions for the second?

**Comment by aanon4** [comment] 2022-08-06 18:09
Circling back on this. Would really like to get some solid and detailed use cases for what people need here. I'm happy to make something happen but I really need to understand what people want very specifically (we've all delivered projects for what we thought people wanted, only to discover they didnt). @dranch @cTurtle98 @KI7ODK. At a basic level I need to write code which makes a decision, using only information the node has to hand, about whether to turn its tunnel on or off.

**Comment by dranch** [comment] 2022-08-06 20:12
AREDN LQM route preference use cases:
08/06/22

Assumption: 
----------------
An AREDN node that has one or more RF mesh uplinks, one or more DtD tunnel uplinks.  DtD links are NOT necessarily Internet based


Use case #1: Prefer RF only
--------------------------------------
If I have a node operating as stated in the assumption section, I would like to have the AREDN node be able to prefer sending traffic over it's RF links ONLY.  This is to keep "traffic over RF" in the spirit of amateur radio.   Only if all RF links are down, should the router use DtD tunnel links if configured this way.  


Use Case #2: Prefer RF DtD links only
----------------------------------------------------
Not all DtD tunnel links should be consider equal.  I believe that some DtD tunnel links could be forwarded over best-of-breed TDMA P2P wireless links over a standard TCP/IP network.  Think of a classic Ubiquiti P2P TDMA link running over 2.4Ghz, 5.8Ghz, 24Ghz, etc. I would like to prefer these DtD tunnels over other DtD links that might be only going over the Internet.  To me, this means that DtD tunnels will need some form of "marking" saying they are "RF based" or not.  I don't believe the AREDN code should try to "auto-detect" if a DtD link is this as there are too many corner cases to consider.


Use Case #3: Redundant DtD links - Prefer one Internet based DtD link over another
----------------------------------------------------------------------------------------------------------------
Not all Internet based DtD tunnel links should be consider equal.  Some of my remote tunnel servers I connect to might be overloaded, might have a slow Internet connection, is unreliable, etc.  It would be good to offer the node operator to set a preferences of which Internet DtD tunnel to use - IN order of some routing metric like weight, etc.


Use Case #4: Prefer Internet connected paths over RF paths when not reachable any other way
------------------------------------------------------------------------------------------------------------------------------
In the SFWEM network, there seems to be a LOT of occurrences where a remote station is reachable via RF but it's effectively NOT reachable.  I don't know if this is an LQM issue, OLSR issue, etc but if possible, it would be ideal to have a given node poll ALL remote destinations and if not reachable via RF, try via DtD tunnel and if reachable there, use the DtD tunnel as the desired nexthop.  This station would need to update this table often to avoid misdirecting or even blackholing traffic.


Use Case #5: Be aware of redundant links and use them when required (do NOT load balance them)
-------------------------------------------------------------------------------------------------------------------------------------
There are times where RF propagation is poor and a given remote path might become unreliable.  In engineered microwave links, the use of vertical antenna or path diversity might be ideal to use if the LQM system can be aware of this:
https://www.microwave-link.com/microwave/space-diversity-in-microwave-links/


Use Case #6: Leverage multiple links and load balance them (possibly out of scope)
---------------------------------------------------------------------------------------------------------------
I believe that in the future, multiple parallel RF links between two specific "backbone" sites might be needed to increase overall performance between these two "backbone" sites.  I don't know if the "routers" hosting these parallel links will make them look as one logical FAT pipe or they will just be seen as multiple constituent network links.  If the "router" is to be a non-AREDN node (probably the best idea), this topic is moot.  If it will be the AREDN node doing this load balancing, I would like to see the AREDN 
firmware offer load balancing support over these multiple constituent network links be it in a per-bit round robin or a more LACP style per-flow load balancing.  I realize this is might be beyond the scope of the LQM system and maybe even the AREDN firmware but I feel this needs to be considered now for the larger future goals of scaling the system.

**Comment by KI7ODK** [comment] 2022-08-06 23:58
Thanks for that explanation @dranch . My view of this request is simpler. I think many of the use cases mentioned here could be met by making one change (simple in my view... may be harder to implement than I think though).

**Current Functionality:** As currently set up, the AREDN firmware has one set weight for tunnel links. This causes an artificial bias, making traffic route over tunnels even when RF links may have high link metrics.

**Request:** Add a setting where users can adjust the weighting given to tunnels. This would mitigate the artificial bias issue and enable users to balance link weights so that high quality RF links are utilized. If an RF link fails, routing could still fall over to a tunnel.

**Comment by mathisono** [comment] 2022-08-07 01:07
OLSRD doesn't have a complex way to describe, complex links, let alone "best quality link". Its clear that RF/ DTD/ Tunnel links have a number of complex properties. As @aanon4 said something "using only information the node has to hand"  Factors that OLSRD was never written monitor.... 

How could links be clearly described for how complex links they are in the REAL world!, in a manner thats able to react too complex changes in the network and not just count packets? 

Q: time to start letting batman-adv make some routing decisions? 
https://www.open-mesh.org/projects/batman-adv/wiki/Tweaking

**Comment by cTurtle98** [comment] 2022-08-07 05:10
just so we dont have confusion over terminology...

d2d / dtd specifically is the vlan2 link between devices physically at the same site.
like 3 rockets on one tower pointed different directions would pass traffic between each other over d2d

tun or tunnel is the traffic over the vpn
the tunnel client and tunnel server tabs in the node interface

what is a d2d/dtd internet based link??

**Comment by aanon4** [comment] 2022-08-07 06:46
@cTurtle98 On some meshes, some sites are connected together using non-AREDN radios (un-flashed Ubiquiti gear for example). Mesh owners have choses to use these links in two ways - either by making them look like VLAN2 and running DtD over them, or by making them look like a WAN and running tunnels over them (there are other options too, but I've not come across them in the wild yet). It's good to have choices, but does add to the complexity when discussing what is needed here.

As AREDN is currently configured, there's an assumption that DtD and AREDN-tunnels will be reliable - or at least, more reliable than wifi links - so all else being equal they'll tend to be preferred assuming they move the packet towards the destination. It's a reasonable assumption when they're used for wire links or wire internet respectively; but that isn't always true now.

@mathisono A switch to batman is a massive project in itself as we cannot just throw away everyones networks and start again - so you need to transition which is a multi-year undertaking. And that assuming anyone understands how well Batman would work in our current environments. The more I learn the more I realize I don't know yet. I'd be very happy to read about someone else's success in similar circumstances.

@KI7ODK As link quality is dynamic, and DtD or tunnels probably don't go to the same exact nodes as the radio links, the question of how to modify the weights to get the desired behavior is not immediate clear to me. Today OLSR manages the routes on a node in an attempt to route a packets towards its destination such that the cost of the links is minimized (cost here is essentially the chance the packet will be lost - it doesn't care about much else). It might be relatively easy to say "this tunnel acts like it looses 50% of the packets" (even if it doesn't) so it's less preferred in some cases, but might still be the best option in some others. It might not be too hard to implement something like this, but does that achieve the goal? Maybe the goal is "if all else fails" in which case perhaps were saying "this tunnel acts like is looses 99.99% of packets" so it will only be used if there really is no other option? You can't say "never use this tunnel unless we need to" because that's too difficult for one node in a network to determine. From a UX perspective, I think it's important that what is implemented does what the user expects when they push the button. Preferring an RF over a Tunnel might still send lots of traffic down the tunnel unless we define what preferred really means. Does that make sense?

**Comment by KI7ODK** [comment] 2022-08-07 12:41
@aanon4 Thanks for the explanation. So if I'm understanding your explanation, link cost is essentially a metric estimating expected packet loss.

Just for my understanding - do nodes have any measure of link latency?

**Comment by aanon4** [comment] 2022-08-07 16:20
You can read about the specifics of the algorithm here - https://github.com/servalproject/olsr/blob/master/README-Olsr-Extensions - we use the ffeth version.

**Comment by aanon4** [comment] 2022-08-17 18:26
After a bunch of discussion I want to propose a specific mechanism for this problem. Credit goes to @dman776 for this, and I think he's come up with something simple but effective:

A tunnel can have an option host (or set of hosts) which is will ping periodically to see if it can be reached. If the host is reachable nothing happens. If the host cannot be reached, the tunnel is activated. The tunnel will remain active so long as the host can only be reached via the tunnel. Once the host can be reached by some other means, the tunnel will be deactivate.

I will gloss over the details of how to make this work (except to say that it's not too difficult and doesn't impose an onerous cost on the node or network) and I expect there are some corner cases to be worked out still.

Feedback from @dranch @cTurtle98 @KI7ODK @mathisono particularly sought.

**Comment by dman776** [comment] 2022-08-17 18:50
thoughts on the name:   "Dynamic tunnels" or "On-demand tunnels"

**Comment by dranch** [comment] 2022-08-17 19:18
I personally don't think this "dynamic tunnels" concept will meet my goal is a good solution for a few reasons:

   1. I would prefer to have the Internet / AREDN VPN tunnel up all the time so I know the end to end tunnel connection is working.  If this was an on-demand tunnel, I wouldn't know if the tunnel can be established until I actually need it but it might not work for a multitude of reasons (remote AREDN node is not reachable due to their node being down, their Internet connection is down, etc)

   2. I and other users on this ticket had also added the ask if it would be possible to have MULTIPLE Internet tunnels present to support having a tunnel "backup".  I suppose dynamic tunnel mechanism could support that but the issue highlighted in issue #1 is still a problem.  If tunnels can be nailed up (like how they function today), I would want a way to prioritize / weight / etc which tunnel would be my primary tunnel if RF fails, which one might be secondary

**Comment by aanon4** [comment] 2022-08-17 20:33
@dranch In the interests of UI simplicity, how coarse a priority set could we get away with? For example, could we *always* have the wifi as preferred? Then tunnels as either "primary" or "secondary" .. both taking a back seat the the wifi?

**Comment by nc8q** [comment] 2022-08-18 10:18
Miami Valley Microwave Alliance, Dayton, Ohio:
We prefer RF paths over tunnels.
All of our routing issues would be solved if tunnels had a weight of 1.0 instead of 0.1.
Even better would be to allow a user defined setting for tunnels from 0.1 to 1.0.

73, Chuck

**Comment by nc8q** [comment] 2022-08-18 10:20
Even mo' better if each tunnel could have an independent weight setting.

**Comment by nc8q** [comment] 2022-08-18 18:10
I want to set the 'cost' of a tunneled path so that it is higher than the RF path cost.
Why is the tunnel cost fixed at 0.1 ?
Why is RF cost fixed at 1.0 ?

**Comment by KI7ODK** [comment] 2022-08-18 18:19
@nc8q  that goes back to OLSR. See the link shared earlier by @aanon4 .
> You can read about the specifics of the algorithm here - https://github.com/servalproject/olsr/blob/master/README-Olsr-Extensions - we use the ffeth version.

**Comment by nc8q** [comment] 2022-08-18 18:48
Within https://github.com/servalproject/olsr/blob/master/README-Olsr-Extensions
is contained:

Building your own LinkQuality Algorithm
----------------------------------------

With the supplied samples OLSRd can be easily extended to support different
metrics. Please take a look at src/lq_plugin*.[ch] for inspiration and get in
contact with us on the OLSR development mailing list in case you plan to
implement a new metric.

**Comment by ae6xe** [comment] 2022-08-18 19:16
re: building your own LinkQuality Algorithm

OLSRv1 (used by AREDN) no longer has the original core development group contributing and adding features.  They have moved on to OLSRv2 and another code repo.   OLSRv1 feature enhancements would end up being done locally with minimal extended community input -- and I'm not working  to dissuade implementing  -- I think it is a great idea to consider.

The challenge we have (implementing locally vs leveraging upstream features) is that jumping to OLSRv2 or Batman would continue to have the same inherit weaknesses of dynamic link state routing algorithms -- delays to propagate to the entire network  (route flapping) and bandwidth taken up to do so.   While moving away from OLSRv1, we would expect to have an incremental improvement dealing with these issues, the benefit hasn't yet been enough to compel the jump and shift focus away from other 'ham' improvements currently occupying contributors' time.  Possibly, there is something with limited effort, that can be done in OLSRv1.  Any significant effort would trigger the thinking to consider jumping to batman.    

Although, for the moment, dynamically taking tunnels in/out of routing consideration (above OLSRv1), may do the trick and we don't need to get to this level of customizing OLSRv1.

**Comment by nc8q** [comment] 2022-08-19 11:37
> Would really like to get some solid and detailed use cases for what people need here. 

[I'm happy to make something happen but I really need to understand what people want very specifically (we've all delivered projects for what we thought people wanted, only to discover they didnt).]

Hi, Tim:
I want tunnels(vtun) to have the same (or user configurable) ETX as Wi-Fi links.
73, Chuck

**Comment by VA2XJM** [comment] 2022-08-19 12:25
@nc8q here are our use cases. Note that our network is not well established yet, this is a work in progress:

- We have a site with LTE backup because the link to that site if just above marginal (we wait for another tower user to move out to place our equipment at the right spot). The cost to run LTE modem there is very high, so we disable tunnel at the other end and activate it when needed. In this case, the "Dynamic Tunnel" solution would be awesome! one less human intervention.
- Dynamic Tunnel could also be generally use if tunnel client is activated at many site as backup only to reduce "load" on tunnel server.
- Right now we have 2 tunnel servers in the region serving as area hub. It would be interesting to be able to set weight so we can set a primary and a secondary link in case of internet outage at one site for islands not yet having RF link. This way we can set priority to where to send the traffic depending on client location and share the load this way.
- Recently, while trying to understand why Zabbix was throwing errors on local systems, I noticed that sometimes OSLR seems to run some traffic through tunnels even when the monitored system is on the same LAN. Adding weight to tunnels fix this.

My view is to have three new parameters added in the GUI for each tunnel client:
- Checkbox for dynamic mode (Default:Uncheck) & textbox to specify host to monitor (Default: empty / Allow WAN/LAN hosts).
- Textbox to specify tunnel weight (Default: 0.1)
This would make updates not breaking things and keep original behaviour.

I think it should cover most of the needs and allow plenty of flexibility.

**Comment by aanon4** [comment] 2022-09-19 22:27
I had hoped someone running tunnels would have provided some feedback on this by now :-(

**Comment by dranch** [comment] 2022-09-19 23:47
In a related discussion on the SFWEM email list, if the NLQ/LQ values are too low, the remote path just won't be considered for for forwarding.  That's *not* the same thing as setting the priority of two or more uplink connections having say similar quality.  Even if we try to use this approach, the next challenge is understanding WHERE to apply this.  Do I apply this on the radio device?  Do I apply it on the hap?  Can you give us a list of commands to run to determine the interface names say on the hap and then an example entry in the olsdrd.conf file?

**Comment by aanon4** [comment] 2022-09-20 00:10
> That's _not_ the same thing as setting the priority of two or more uplink connections having say similar quality

But I don't know that this means in practice. Are two links with different priorities going to be between the same two nodes? If so then a priority is easy to define. If not, then what does it mean to have two priorities on two links which are not otherwise equivalent?

Regarding the NLQ/LQ values - when one drops very low (approaching 0) the ETX value calculated for the link (which is what the routing protocol uses to makes its decisions) approaches infinity, and so the link is ignored. But there are many other values which have more subtle effects. Disregarding ethernet for the moment, an ETX of 1 essentially means "1 hop". An ETX of 2 means "2 hops". At its very simplest, OLSR calculated the best route between two nodes by determining the minimum total ETX of the paths between them. So if I node were to artificially increase its ETX on a link to 5, its essentially saying "this  link is like 5 links" to the routing algorithm. This actually seems like a useful way to make a link less desirable in a way that's easy to understand. If we were to add a priority to that link I'm not sure what it would mean, from a routing perspective, if there's no otherwise equivalent link. Other link state algorithms (OSPF for example) use a cost per link and while that cost is derived differently, the final calculate uses the same least-cost routing algorithm as OLSR.

Getting back to my original question - what does priority mean to you? And how does that effect a network of node determining the best path between each other when every node could set a priority for every link? Given how the routing algorithm works, how is this priority information represented to the system as whole, and how does it change how the least-cost routing algorithm behave?

**Comment by dranch** [comment] 2022-09-20 20:35
If I change the qualities of an Internet tunnel to the point that the AREDN node will no longer select it and instead, use the RF link for frowarding... what will happen in the RF link fails?  I believe the answer is the node will go offline as the Internet tunnel's quality is too low to be viable for any forwarding.   As I read from https://sites.google.com/site/orangecountymeshorganization/lqnlqandetx , ETX is calculated from the NLQ and LQ values based upon each node on each side of a given link confirming if they are receiving all of the expected OLSR advertisements or not.  There doesn't seem to be any other way to "add" or "subtract" from it's value.

Anyway, back to my my original ask here:  at an example site where my traffic comes in via an RF node which is then connected to a Hap via a DTD link (which also has an Internet tunnel but also other RF uplink radios), I want my my original traffic to STAY on RF only links if possible.  I really only want to have my Internet to go over an Internet link as a last resort.  To me, there needs to be some other kind of metric to make the final forwarding decisions than NLQ, LQ, and ETX as those are all really more centric to RF related paths and is meaningless for less error prone Internet links.

**Comment by aanon4** [comment] 2022-09-20 21:51
> If I change the qualities of an Internet tunnel to the point that the AREDN node will no longer select it and instead, use the RF link for frowarding... what will happen in the RF link fails? I believe the answer is the node will go offline as the Internet tunnel's quality is too low to be viable for any forwarding. 

So no. If there are two links - one cheap, one expensive - and the cheap one is down, the system uses the expensive one. At that point its the cheapest option available.

> As I read from https://sites.google.com/site/orangecountymeshorganization/lqnlqandetx , ETX is calculated from the NLQ and LQ values based upon each node on each side of a given link confirming if they are receiving all of the expected OLSR advertisements or not. There doesn't seem to be any other way to "add" or "subtract" from it's value.

The value can be scaled using the "LinkQualityMult" config option. Suppose this value was 0.1, the ETX is now a 1/10th its calculated value, making that link look like a 10-hop link rather than a 1-hop link (each hop in a perfect radio network has an ETX of 1). It'd be easy enough to add an option to add/subtract to the ETX value of a link.

> 
> Anyway, back to my my original ask here: at an example site where my traffic comes in via an RF node which is then connected to a Hap via a DTD link (which also has an Internet tunnel but also other RF uplink radios), I want my my original traffic to STAY on RF only links if possible. I really only want to have my Internet to go over an Internet link as a last resort. To me, there needs to be some other kind of metric to make the final forwarding decisions than NLQ, LQ, and ETX as those are all really more centric to RF related paths and is meaningless for less error prone Internet links.

Most nodes have many links, some DtD, some tunnels, some radios (and radios can have many links on the same radio). If you wish to only use a tunnel under some situations, I need a way to define that situation in a way which doesnt assume the node is a simple leaf with only one RF link. Most nodes aren't like that and it's why I'm struggling to generalize the requirements.

A while back we proposed a solution where the node monitored a specific remote node(s) and, if not available, would activate the tunnel (whether the tunnel is active, but unused, or established in the moment is somewhat orthogonal here - both options are easy enough). Reading back, this still seems to provide you with what you want. Then there's the issue of a tunnel priority, and beyond the binary on/off nature described here, this can be expressed in terms of their cost in relation to other links in the network using the LinkQualityMult option.

What am I missing? Assuming I am, can you describe what you'd want for a node with multiple links in/out and when and how it would decide to "active" a tunnel? In the last week we've had a few cases in the Bay where the network become partitioned, and some automatic tunnel would have been great. Importantly though this wasn't one leaf node falling off, but the failure of several links simultaneously.

**Comment by KI7ODK** [comment] 2022-10-04 12:57
@aanon4 I think the solution you mentioned of having a node monitor a specific remote node would work pretty well (at least in my mind). Having an option to modify (add/subtract) the ETX value of a link is more inline with what I was originally thinking.

The kicker will be to see how either of these options behave in practice...

**Comment by nc8q** [comment] 2022-10-11 08:13
On 9/19/22 18:27, Tim Wilkinson wrote:
> I had hoped someone running tunnels would have provided some feedback 
> on this by now :-(

Hi, Tim et alia:

If each tunnel's ETX was 2 instead of 0.1, it would allow our network to 
'fallback to tunnel' if a RF path failed.
Currently we have a 'man in the middle' with two tunnels to two ends of 
our network.
If we have both his tunnels enabled, the double-tunnel ETX wins over the 
3 hop RF path.

73, Chuck

**Comment by nathantcampbell** [comment] 2022-11-29 00:37
Chiming in on this discussion as we've had similar issues in the Willamette Valley Mesh Network. Our problem is our network has grown large enough where the 0.1 ETX of tunnels will route through 9x tunnels hops (many of which are between separate ISPs which exchange 100+ miles away) before going through a single hop RF link due to the ETX value skewing. In many cases our RF links are better than what most people have at home in terms of upload bandwidth and latency (mostly due to distant peering arrangements mentioned above). 

At a minimum, I think either allowing adjustment of the tunnels to ~1 ETX value would help our situation a lot putting it on a more level playing field as RF or if setting ETX higher for the routing to prefer RF before the tunnel, making it more of a backup. In addition, the designated tunnel backup options sounds nice for certain use cases we're drumming up in Lane county as we prepare to locate a server in the Willamette Internet Exchange which could facilitate backup tunnel links across local ISP's networks but only be "lit up" if our primary RF links fail.

Best case, I'd love if there was a simple way to rank tunnels 1>infinity ETX based on metrics similar to what we do on RF so poor tunnels are deprioritized for routing while good tunnels or RF are higher prioritized. I doubt that would be easy to do though with metrics that are meaningful enough to solve the various issues people have seen as it would likely need to consider latency/jitter/throughput all of which may put too much strain on the hardware to gauge with adequate frequency.

**Comment by K1RKS** [comment] 2023-05-23 16:25
I looked into the OLSRD source files, and the config file specifically:
/tmp/etc/olsrd.conf   (and yes I understand this is a memory temporary version used for example).

The OLSRD "cost" calculator has a special test for "ether" (basically if NQ/NLQ are magic values it sets it to ether mode and that is where you get the "0.1" value .. technically it is 1.0/10.

Here I am making an assumption .. but the config file "olsrd.conf" appears to assign "modes" to interfaces.  Valid modes appear to be "mesh" and "ether".  So my assumption here is ... interfaces flagged as "ether" get the magic value assigned to them so that when OLSRD assigns a cost it goes to the "0.1" value.

For example my  hAP has the following:

Interface "br-dtdlink"
{
        Mode "ether"
}

Interface "tun60" "tun61"
{
     Ip4Broadcast 255.255.255.255
     Mode "ether"
}

I had another HAM verify their RF node had an interface that said "mesh" ... 

So would it be possible to have an advanced option (or ideally on each tunnel setting) .. the ability to choose if this tunnel is "mesh" or "ether" ... then at least we could have tunnels appear to be RF in their cost and *NOT* get chosen over local RF that are dtd connected?

Might be a step in the right direction that doesn't cause a change to the core OSLRD code at all.
After that I was going to look into the idea of adding a third type.

`const char *OLSR_IF_MODE[] = {
  "mesh",
  "ether",
  "tun"         // Tunnel devices
};
`
That way we could setup a separate "tunnel" cost modifier like we do "ether" (and then each node could choose if a tunnel connection is  better / worse / same as a ether or mesh.

Either way I think this could be tested by manually changing the oslrd.conf and restarting oslrd if I am understanding the code correctly (forgive me I only had 30mins to skim the C code ... so I have almost no understanding of the architecture at this point).

**Comment by aanon4** [comment] 2023-05-23 20:16
There are two problems you need to contend with:
1. What does 'tun' mean here? "ether" is used to convey a very specific weighting for a connection to other nodes by sending a reserved value which other nodes understand. What does tun mean to them?
2. We will always have old nodes running which wont understand whatever the 'tun' value is being send to them, so how do we handle this?

There is a 'weight' option you can set in /etc/config.mesh/aredn like this:
```
config tunnel                                                                   
        option maxclients '10'
        option maxservers '10'
        option weight '3' 
```
A value of 0 means 'ether', 1 means 'RF/mesh' (the default) and then 2, 3, 4 ... etc means a worse kind of RF. You can use it to make tunnels less preferred, but they're not ignored - just less used.

**Comment by nathantcampbell** [comment] 2023-05-23 21:44
Hi Tim,

Are we planning on adding the tunnel weight setting to the advanced page?
At the moment it appears we have the maxclients and maxservers mapped to
the advanced page but not yet the option weight.

Aside from the optional weight of 0 mapping to 0.1 ETX, does setting it to
1 map to ETX of 1, 2>2, and so on? Does this only work in whole integers or
can we do tenths? (eg 1.1)?


Nathan Campbell

**Comment by aanon4** [comment] 2023-05-23 21:59
It hasnt been added to the advanced config page mostly because we've not decided if tinkering with this is a good solution to the problem. If you play with it by hand it would be good to get some feedback.

And yes, your mapping is correct and, unfortunately, it can only be an integer.

**Comment by ae6xe** [comment] 2023-05-23 22:41
In the usage of "ether",  there was another consideration as I recall.    There are also threshold values.  OSLR will drop the layer 3 link, or re-establish at given thresholds.     On a RF mesh link, the thresholds are, example 40% and 80%, meaning  if the LQ/NLQ quality of the link drops down past 40%, then olsr will drop the route from the routing table. When the quality raises back up to 80% it will add the link back to the routing table.   With Ether mode, it is something like 85% and 95%?  

This doesn't always apply.  If an interface is riding over the top of another RF link, depending on the setup, it may be 100% quality at all times.   When the data is encapsulated over a tunnel, the RF lower layer will give guaranteed delivery of this unicast tunnel traffic.    The broadcast is inside the tunnel.   Where thresholds may apply is probably when 2 devices are in bridge mode for the RF layer and dtdlink is raw over the link doing broadcast on the RF, then the threshold issue comes into play.  The link bounces too often as the drop out threshold is too high. 

All of this to say, to set a link to 0.1 ETX for the weighting, setting mode ether, may or may not create other problems.

**Comment by K1RKS** [comment] 2023-05-24 16:28
So the first primary issue is "we don't want tunnels to appear as dtd interfaces".   This appears to create routing problems especially when a tunnel is on a node with multiple RF paths that are on the same switch.  (From the node's point of view it can choose several RF devices that are DTD, or send it out a tunnel that also appears to be a DTD ... and the problem is the tunnel sends it to the other side of the net were the RF paths are distant.  Rather than using the 1 - hop RF that was on the DTD link.

So what I was suggesting was the ability of a node to say "This tunnel interface is 'mesh'"  rather than the current default of 'ether'.    If I read the olsrd.conf correctly .. that config controls what "mode" an interface is tagged as.

**Comment by aanon4** [comment] 2024-08-18 23:28
Individual tunnel weights are now supported.

**Closed by aanon4** 2024-08-18 23:28 UTC
Labels: enhancement

**Comment by K1RKS** [comment] 2024-08-18 23:30
Great thanks so much!

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by nc8q** [comment] 2024-08-19 10:34
"Individual tunnel weights are now supported."
Marvelous!
I look forward to trying this.

**Comment by nc8q** [comment] 2024-08-19 10:36
On 8/18/24 19:29, Tim Wilkinson wrote:
>
> Individual tunnel weights are now supported.
>
>
:-) Thanks.
